- reference-client/pom.xml
- reference-service/pom.xml
Reverts Health-Education-England/TIS-REFERENCE#137
> Revert "chore(deps): bump springfox.version from 2.8.0 to 3.0.0"

- reference-client/pom.xml
- reference-client/src/main/java/com/transformuk/hee/tis/reference/client/ReferenceService.java
- reference-client/src/main/java/com/transformuk/hee/tis/reference/client/impl/ReferenceServiceImpl.java
- reference-client/src/test/java/com/transformuk/hee/tis/reference/client/impl/ReferenceServiceImplTest.java
For placementGrade and trainingGrade = true
TIS21-1622
> feat: new client endpoint for current grades

- reference-client/pom.xml
- reference-service/pom.xml
> chore: bump tis_security_jwt version

- Jenkinsfile
Currently the pipeline is failing the health-check, see if this fixes
that issue.
NO-TICKET
> fix: increase Jenkins stage-check timeout

- Jenkinsfile
> fix: correct jenkins milestone

- .aws/task-definition-template.json
- .github/workflows/ci-cd-workflow.yml
Create a workflow in GHA to deploy to ECS.
Create a task definition template that can be shared across all
environments, the workflow should replace a variable with the correct
value for the environment being deployed to.
TIS21-2730
> feat: create ci/cd workflow in GitHub Actions

- reference-client/pom.xml
- reference-client/src/main/java/com/transformuk/hee/tis/reference/client/impl/ReferenceServiceImpl.java
- reference-client/src/test/java/com/transformuk/hee/tis/reference/client/impl/ReferenceServiceImplTest.java
- reference-service/pom.xml
- reference-service/src/main/java/com/transformuk/hee/tis/reference/service/api/RoleResource.java
- reference-service/src/test/java/com/transformuk/hee/tis/reference/service/api/RoleResourceIntTest.java
> fix: add a new endpoint to query roles by multiple roles

- .github/workflows/ci-cd-workflow.yml
aws-actions/configure-aws-credentials from v1 to v2
TIS21-4361
> chore:bump version of a github action

- .aws/task-definition-template.json
- reference-service/pom.xml
- reference-service/src/main/resources/config/application.yml
- reference-service/src/main/resources/logback-spring.xml
Please DON'T MERGE until the SENTRY_DSN ssm parameter is created.
TIS21-4560
> feat: add sentry configuration

- reference-client/pom.xml
- reference-client/src/main/java/com/transformuk/hee/tis/reference/client/impl/ReferenceServiceImpl.java
- reference-client/src/test/java/com/transformuk/hee/tis/reference/client/impl/ReferenceServiceImplTest.java
- reference-service/src/main/resources/config/application.yml
> refactor:log level for Sites/Grades not found

- reference-client/pom.xml
- reference-client/src/main/java/com/transformuk/hee/tis/reference/client/ReferenceService.java
- reference-client/src/main/java/com/transformuk/hee/tis/reference/client/impl/ReferenceServiceImpl.java
- reference-client/src/test/java/com/transformuk/hee/tis/reference/client/impl/ReferenceServiceImplTest.java
- reference-service/pom.xml
- reference-service/src/main/java/com/transformuk/hee/tis/reference/service/api/LeavingReasonResource.java
- reference-service/src/main/java/com/transformuk/hee/tis/reference/service/api/ProgrammeMembershipTypeResource.java
- reference-service/src/test/java/com/transformuk/hee/tis/reference/service/api/LeavingReasonResourceIntegrationTest.java
- reference-service/src/test/java/com/transformuk/hee/tis/reference/service/api/ProgrammeMembershipTypeResourceIntTest.java
/api/programme-membership-types/exist
/api/leaving-reasons/exist
TIS21-3785
> feat:add endpoints for pm fields validation

- reference-api/pom.xml
- reference-api/src/main/java/com/transformuk/hee/tis/reference/api/dto/FundingTypeDTO.java
- reference-client/pom.xml
- reference-service/pom.xml
- reference-service/src/main/java/com/transformuk/hee/tis/reference/service/api/FundingTypeResource.java
- reference-service/src/main/java/com/transformuk/hee/tis/reference/service/model/FundingType.java
- reference-service/src/main/resources/db/migration/common/V3.68__change_funding_type_field_name.sql
- reference-service/src/test/java/com/transformuk/hee/tis/reference/service/api/FundingTypeResourceIntTest.java
> fix: rename funding type field

- reference-service/src/main/resources/db/migration/common/V3.70_create_funding_sub_type_table.sql
- reference-service/src/main/resources/db/migration/common/V3.71__create_funding_sub_type_table.sql
TIS21-5379: To create a new table in database to store sub-categories
> feat: add funding sub type table

- .github/workflows/ci-cd-workflow.yml
> chore:upgrade java to 17 in cicd workflow

- reference-client/pom.xml
- reference-client/src/main/java/com/transformuk/hee/tis/reference/client/ReferenceService.java
- reference-client/src/main/java/com/transformuk/hee/tis/reference/client/impl/ReferenceServiceImpl.java
- reference-client/src/test/java/com/transformuk/hee/tis/reference/client/impl/ReferenceServiceImplTest.java
- reference-service/pom.xml
- reference-service/src/main/java/com/transformuk/hee/tis/reference/service/api/FundingSubTypeResource.java
Those new methods will be used for fundingSubType validation
TIS21-5383
> feat:add client methods for fundingSubType

- reference-api/pom.xml
- reference-api/src/main/java/com/transformuk/hee/tis/reference/api/dto/LocalOfficeContactDto.java
- reference-api/src/main/java/com/transformuk/hee/tis/reference/api/dto/LocalOfficeContactTypeDto.java
- reference-service/pom.xml
- reference-service/src/main/java/com/transformuk/hee/tis/reference/service/aop/auditing/AuditingAspect.java
- reference-service/src/main/java/com/transformuk/hee/tis/reference/service/api/LocalOfficeContactResource.java
- reference-service/src/main/java/com/transformuk/hee/tis/reference/service/api/LocalOfficeContactTypeResource.java
- reference-service/src/main/java/com/transformuk/hee/tis/reference/service/model/LocalOffice.java
- reference-service/src/main/java/com/transformuk/hee/tis/reference/service/model/LocalOfficeContact.java
- reference-service/src/main/java/com/transformuk/hee/tis/reference/service/model/LocalOfficeContactType.java
- reference-service/src/main/java/com/transformuk/hee/tis/reference/service/repository/LocalOfficeContactRepository.java
- reference-service/src/main/java/com/transformuk/hee/tis/reference/service/repository/LocalOfficeContactTypeRepository.java
- reference-service/src/main/java/com/transformuk/hee/tis/reference/service/service/impl/LocalOfficeContactServiceImpl.java
- reference-service/src/main/java/com/transformuk/hee/tis/reference/service/service/impl/LocalOfficeContactTypeServiceImpl.java
- reference-service/src/main/java/com/transformuk/hee/tis/reference/service/service/mapper/LocalOfficeContactMapper.java
- reference-service/src/main/java/com/transformuk/hee/tis/reference/service/service/mapper/LocalOfficeContactTypeMapper.java
- reference-service/src/main/resources/db/migration/common/V3.73__create_local_office_contact_types.sql
- reference-service/src/test/java/com/transformuk/hee/tis/reference/service/api/LocalOfficeContactResourceIntTest.java
- reference-service/src/test/java/com/transformuk/hee/tis/reference/service/api/LocalOfficeContactTypeResourceIntTest.java
- reference-service/src/test/java/com/transformuk/hee/tis/reference/service/api/LocalOfficeResourceIntTest.java
Create LocalOfficeContactType and LocalOfficeContact reference types to facilitate the recording of contact details for local offices.
Each Local Office should only be allowed to have one of each contact type.
TIS21-5705
TIS21-5668
> feat: local office contact reference types

- reference-service/pom.xml
- reference-service/src/main/java/com/transformuk/hee/tis/reference/service/api/LocalOfficeContactResource.java
- reference-service/src/main/java/com/transformuk/hee/tis/reference/service/api/validation/LocalOfficeContactValidator.java
- reference-service/src/test/java/com/transformuk/hee/tis/reference/service/api/LocalOfficeContactResourceIntTest.java
- reference-service/src/test/java/com/transformuk/hee/tis/reference/service/api/validation/LocalOfficeContactValidatorTest.java
Validate the LocalOfficeContacts are valid email addresses or HTTPS URLs.
TIS21-5727
TIS21-5668
> feat: validate Local Office contact details

- reference-service/pom.xml
- reference-service/src/main/java/com/transformuk/hee/tis/reference/service/model/AssessmentType.java
- reference-service/src/main/java/com/transformuk/hee/tis/reference/service/model/College.java
- reference-service/src/main/java/com/transformuk/hee/tis/reference/service/model/Country.java
- reference-service/src/main/java/com/transformuk/hee/tis/reference/service/model/CurriculumSubType.java
- reference-service/src/main/java/com/transformuk/hee/tis/reference/service/model/DBC.java
- reference-service/src/main/java/com/transformuk/hee/tis/reference/service/model/EthnicOrigin.java
- reference-service/src/main/java/com/transformuk/hee/tis/reference/service/model/FundingType.java
- reference-service/src/main/java/com/transformuk/hee/tis/reference/service/model/GdcStatus.java
- reference-service/src/main/java/com/transformuk/hee/tis/reference/service/model/Gender.java
- reference-service/src/main/java/com/transformuk/hee/tis/reference/service/model/GmcStatus.java
- reference-service/src/main/java/com/transformuk/hee/tis/reference/service/model/Grade.java
- reference-service/src/main/java/com/transformuk/hee/tis/reference/service/model/LocalOffice.java
- reference-service/src/main/java/com/transformuk/hee/tis/reference/service/model/MaritalStatus.java
- reference-service/src/main/java/com/transformuk/hee/tis/reference/service/model/MedicalSchool.java
- reference-service/src/main/java/com/transformuk/hee/tis/reference/service/model/Nationality.java
- reference-service/src/main/java/com/transformuk/hee/tis/reference/service/model/OrganizationType.java
- reference-service/src/main/java/com/transformuk/hee/tis/reference/service/model/PermitToWork.java
- reference-service/src/main/java/com/transformuk/hee/tis/reference/service/model/PlacementType.java
- reference-service/src/main/java/com/transformuk/hee/tis/reference/service/model/ProgrammeMembershipType.java
- reference-service/src/main/java/com/transformuk/hee/tis/reference/service/model/ReligiousBelief.java
- reference-service/src/main/java/com/transformuk/hee/tis/reference/service/model/Role.java
- reference-service/src/main/java/com/transformuk/hee/tis/reference/service/model/RoleCategory.java
- reference-service/src/main/java/com/transformuk/hee/tis/reference/service/model/Settled.java
- reference-service/src/main/java/com/transformuk/hee/tis/reference/service/model/SexualOrientation.java
- reference-service/src/main/java/com/transformuk/hee/tis/reference/service/model/Title.java
- reference-service/src/main/resources/db/migration/common/V3.76__fix_corrupted_uuids.sql
- reference-service/src/main/resources/db/migration/tenant/hee/V3.75__fix_corrupted_uuids_prod_only.sql
- reference-service/src/main/resources/db/migration/tenant/nimdta/V3.74__fix_corrupted_uuids_nimdta_only.sql
1. add uuid generator strategy and type on entities;
2. fix existing corrupted uuids.
TIS21-5733
> fix:corrupted uuids

- reference-service/src/main/resources/db/migration/tenant/nimdta/V3.74__fix_corrupted_uuids_nimdta_only.sql
> fix:quotes for NIMDTA script.

- reference-service/src/main/resources/db/migration/tenant/nimdta/V3.77__update_uuids_to_match_prod.sql
> fix:update NIMDTA uuids to match new prod values.

- reference-service/pom.xml
- reference-service/src/main/java/com/transformuk/hee/tis/reference/service/api/NationalityResource.java
- reference-service/src/test/java/com/transformuk/hee/tis/reference/service/api/NationalityResourceIntTest.java
> fix:nationality to use correct field to check its existence.

- reference-client/pom.xml
- reference-client/src/main/java/com/transformuk/hee/tis/reference/client/ReferenceService.java
- reference-client/src/main/java/com/transformuk/hee/tis/reference/client/impl/ReferenceServiceImpl.java
- reference-client/src/test/java/com/transformuk/hee/tis/reference/client/impl/ReferenceServiceImplTest.java
- reference-service/pom.xml
- reference-service/src/main/java/com/transformuk/hee/tis/reference/service/api/DBCResource.java
- reference-service/src/main/java/com/transformuk/hee/tis/reference/service/repository/DBCRepository.java
- reference-service/src/test/java/com/transformuk/hee/tis/reference/service/api/DBCResourceIntTest.java
This will be required by the tis-sync service to act on requests from TSS for local offices where the DBC record exists in TSS but the linking abbreviation is not matched to a local office record, and vice-versa.
TIS21-6273
TIS21-6279
> feat: find localoffices and DBCs by abbreviation

- reference-service/pom.xml
- reference-service/src/main/java/com/transformuk/hee/tis/reference/service/service/mapper/DbcToLocalOfficeMapper.java
- reference-service/src/test/java/com/transformuk/hee/tis/reference/service/api/LocalOfficeResourceIntTest.java
- reference-service/src/test/java/com/transformuk/hee/tis/reference/service/service/mapper/DbcToLocalOfficeMapperTest.java
> fix:update DBC mapper

- reference-service/pom.xml
- reference-service/src/main/resources/db/migration/common/V3.81__create_funding_reason_table.sql
TIS21-5471: Add a new reference table in the DB
> feat: add post funding reason reference table

- reference-service/src/main/java/com/transformuk/hee/tis/reference/service/aop/auditing/AuditingAspect.java
TIS21-5472: Add a new endpoint for the dropdown list
> fix: map funding reason ID to UUID Type from JSON request object

- reference-service/pom.xml
- reference-service/src/main/resources/db/migration/common/V3.82__update_local_office_abbreviations.sql
TIS21-6458: Update Local Office abbreviation
> feat: update local office abbreviations

- reference-api/pom.xml
- reference-client/pom.xml
- reference-service/Dockerfile
- reference-service/pom.xml
> chore: upgrade profile, docker, and java version
